CREATE TABLE IF NOT EXISTS `%s` (
  `gps_id` int(11) NOT NULL auto_increment,
  `gps_name` varchar(32) default NULL,
  `gps_host` varchar(32) default NULL,
  `gps_type` varchar(10) default NULL,
  `gps_utc_coord` int(11) default NULL COMMENT 'in UTC (coordinated universal time zone). UTC used be known as GMT',
  `gps_status` char(1) default NULL COMMENT 'Status A = Valid, V = Invalid',
  `gps_latitude` varchar(16) default NULL COMMENT 'latitude of the GPS position fix',
  `gps_ns` char(1) default NULL COMMENT 'N/S Indicator S N = North, S = South',
  `gps_longitude` varchar(16) default NULL COMMENT 'longitude of the GPS position fix',
  `gps_ew` char(1) default NULL COMMENT 'E/W Indicator E E = East, W = West',
  `gps_speed` float default NULL COMMENT 'Speed over ground in Knots',
  `gps_course` float default NULL COMMENT 'Course over ground 0.00 Degrees',
  `gps_utc_date` int(11) default NULL COMMENT 'UTC Date 211200 DDMMYY',
  `gps_mvd` float default NULL COMMENT 'Magnetic variation Degrees',
  `gps_mv` char(1) default NULL COMMENT 'mv',
  `gps_cs` varchar(100) default NULL COMMENT 'Checksum *25',
  `gps_msg_ori` varchar(1024) default NULL,
  `gps_time` timestamp NULL default NULL,
  `gps_latitude_real` double default NULL,
  `gps_longitude_real` double default NULL,
  `gps_odometer` double default NULL,
  `gps_workhour` int(11) default NULL,
  PRIMARY KEY  (`gps_id`),
  KEY `NewIndex3` (`gps_name`,`gps_host`),
  KEY `NewIndex1` (`gps_utc_coord`),
  KEY `NewIndex4` (`gps_utc_date`),
  KEY `gps_park_index` (`gps_name`,`gps_host`,`gps_time`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1
