version: '3'
services:
  # PHP Application
  php:
    image: php:7.4-apache
    container_name: transporter
    volumes:
      - ./php-app:/var/www/html
    ports:
      - "8181:81"
    depends_on:
      - mysql

  # MySQL Database
  mysql:
    image: mysql:5.7
    container_name: my-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: transporter
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
