<?php
		$config['iscustompage'] = true;
		$config['template'] = 'balrich/';
		$config['logout'] = 'http://balrich.lacak-mobil.com';
		$config['favicon'] = "assets/transporter/images/truck_blue.ico";
		$config['license'] = "www.lacak-mobil.com";
		$config['dir_photo'] = "assets/transporter/images/photo/";
		$config['default_photo_driver'] = "default_photo_driver.png";
		$config['transporter_user_type_name'] = "Regular";
        $config['transporter_agent'] = 1;
		$config["interval_notification"] = 10000; //10 Detik
		$config["interval_geofence_alert"] = 20000; //20 Detik 
		$config["interval_get_geofence_alert"] = 30000; //30 Detik 	
		$config["vehicle_detail_app"] = 1; // TRUE
		$config["since_at_geofence"] = 1; // TRUE
        $config["download_report_path"] = "http://balrich.lacak-mobil.com/assets/media/autoreport/";
		$config["comment_app"] = 1; //comment aplication
		$config["fan_app"] = 1; //Use Fan Application
		$config['GOOGLE_MAP_API_KEY'] = "AIzaSyAdeQ7MX2Uho9Pt6CuU_qSadtnpjQG9wjU";
