<?php
	$config['default_gpstable'] = "gps";
	
	$config['vehicle_T1'] = array("T1", 
								"T1_1", 
								"T1_U1", 
								"PLN");
								
	$config['vehicle_type'] = array('T1'=>'gprmc', 
									'T3'=>'sms', 
									'T4'=>'gtp', 
									"indogps"=>"indogps", 
									'T4 Farrasindo'=>'farrasindo', 
									'T1_1'=>'T1_1', 
									"pln"=>"pln", 
									"T4 Andalas"=>"gtp_andalas", 
									"T4 Agung Putra"=>"agungputra", 
									"T4 New"=>"gtp_new", 
									"T1_U1"=>"t1_2", 
									"T5"=>"t5", 
									"T5 PULSE"=>"t5_pulse", 
									"T5 Fuel"=>"t5_fuel", 
									"T5 2WAY"=>"t5_2way", 
									"T5DOOR"=>"T5DOOR", 
									"T5FAN"=>"T5FAN", 
									"T5PTO"=>"T5PTO", 
									"T5SUHU"=>"T5SUHU",
									"T5TAXI"=>"T5TAXI", 
									"T5SILVER"=>"T5SILVER", 
									"T8"=>"T8", 
									"T8_2"=>"T8_2", 
									"TK303"=>"TK303",
									"TK309"=>"TK309",
									"TK309PTO"=>"TK309PTO",
									"TK309N"=>"TK309N",
									"TK309_NEW"=>"TK309_NEW",
									"TK309LSA"=>"TK309LSA",
									"TK315"=>"TK315",
									"TK315DOOR"=>"TK315DOOR",
									"TK315N"=>"TK315N",
									"TK315DOOR_NEW"=>"TK315DOOR_NEW",
									"TK315_NEW"=>"TK315_NEW",
									"TK315FAN"=>"TK315FAN",
									"TK315LSA"=>"TK315LSA",
									"TK510"=>"TK510",
									"TK510FAN"=>"TK510FAN",
									"TK510DOOR"=>"TK510DOOR",
									"TK510CAM"=>"TK510CAM",
									"TK510CAMDOOR"=>"TK510CAMDOOR",
									"T13"=>"T13",
									"TK05"=>"TK05",
									"TJAM"=>"TJAM", 
									"T6"=>"t6", 
									"T7"=>"t7", 
									"TMOTOR"=>"TMOTOR",
									"GT08S"=>"GT08S",
									"GT08SFAN"=>"GT08SFAN",
									"GT08SPTO"=>"GT08SPTO",
									"GT08SRFID"=>"GT08SRFID",
									"GT08SDOOR"=>"GT08SDOOR",
									"GT08"=>"GT08",
									"GT08FAN"=>"GT08FAN",
									"GT08PTO"=>"GT08PTO",
									"GT08CAM"=>"GT08CAM",
									"GT08DOOR"=>"GT08DOOR",
									"GT08CAMDOOR"=>"GT08CAMDOOR",
									"GT06"=>"GT06",
									"GT06PINS"=>"GT06PINS",
									"GT06N"=>"GT06N",
									"GT06_NEW"=>"GT06_NEW",
									"A13"=>"A13",
									"A14"=>"A14",
									"AT5"=>"AT5",
									"AT09"=>"AT09",
									"X3"=>"X3",
									"X3_DOOR"=>"X3_DOOR",
									"X3_PTO"=>"X3_PTO",
									"LT02"=>"LT02",
									"LT03"=>"LT03",
									"MT05S"=>"MT05S",
									"NR"=>"NR",
									"NDROID"=>"NDROID",
									"WETRACK"=>"WETRACK",
									"MV03"=>"MV03",
									"VT900"=>"VT900",
									"VT900DOOR"=>"VT900DOOR",
									"VT900FAN"=>"VT900FAN",
									"VT900PTO"=>"VT900PTO",
									"VT900BIB"=>"VT900BIB",
									"VT100"=>"VT100",
									"VT200"=>"VT200",
									"VT200DOOR"=>"VT200DOOR",
									"VT200FAN"=>"VT200FAN",
									"VT200PTO"=>"VT200PTO",
									"VT200BIB"=>"VT200BIB",
									"HVT001"=>"HVT001",
									"MVT340"=>"MVT340",
									"VT202"=>"VT202",
									"VT203"=>"VT203",
									"AT5_RBT"=>"AT5_RBT"
									);
	
	$config['vehicle_type_admin'] = array("T4 Farrasindo", 
											"pln", 
											"T4 Agung Putra");
	
	$config['vehicle_type_visible'] = array('T1', 
											'T3', 
											'T4', 
											'indogps', 
											'T4 Farrasindo', 
											'pln', 
											"T4 Agung Putra", 
											"T4 New", 
											"T1_U1", 
											"T5", 
											"T5 PULSE", 
											"T5 Fuel", 
											"T5 2WAY", 
											"T5DOOR", 
											"T5FAN", 
											"T5PTO", 
											"T5TAXI", 
											"T5SILVER", 
											"T5SUHU",
											"T6", 
											"T7", 
											"T8", 
											"T8_2",
											"TK303", 
											"TK309",
											"TK309PTO", 
											"TK309N",
											"TK309_NEW",
											"TK315",
											"TK315DOOR",
											"TK315N",
											"TK315DOOR_NEW",
											"TK315_NEW",
											"TK510",
											"TK510FAN",
											"TK510PTO",
											"TK510DOOR",
											"TK510CAM",
											"TK510CAMDOOR",
											"TK315FAN",
											"TK315LSA",
											"TK309LSA",
											"T13",
											"TK05",
											"GT06",
											"GT06PINS",
											"GT06N",
											"GT06_NEW",
											"GT08S",
											"GT08SRFID",
											"GT08SFAN",
											"GT08SPTO",
											"GT08SDOOR",
											"GT08",
											"GT08FAN",
											"GT08PTO",
											"GT08CAM",
											"GT08DOOR",
											"GT08CAMDOOR",
											"TJAM", 
											"TMOTOR", 
											"A13", 
											"A14", 
											"AT5",
											"AT09",
											"LT02",
											"LT03",
											"MT05S",
											"X3",
											"X3_DOOR",
											"X3_PTO",
											"NR",
											"NDROID",
											"WETRACK",
											"MV03",
											"VT900",
											"VT900DOOR",
											"VT900FAN",
											"VT900PTO",
											"VT900BIB",
											"VT100",
											"VT200",
											"VT200DOOR",
											"VT200FAN",
											"VT200PTO",
											"VT200BIB",
											"HVT001",
											"MVT340",
											"VT202",
											 "VT203",
											 "AT5_RBT"
											 
											); 
											
	$config['vehicle_type_replace'] = array('T1'=>'T1_1');	
	
	$config['vehicle_image'] = array("car"=>"lcar", 
									"truck"=>"ltruck", 
									"dot"=>"ldot", 
									"strada"=>"lstrada", 
									"pickup"=>"lpickup", 
									"innova"=>"linnova", 
									"daf"=>"ldaf", 
									"excavator"=>"lexcavator", 
									"motor"=>"lmotor",
									"truck_crane"=>"ltruck_crane", 
									"truck_mixer"=>"ltruck_mixer", 
									"truck_hijau"=>"ltruck_hijau", 
									"wheel_loader"=>"lwheel_loader", 
									"crawler"=>"lcrawler");
									
	$config['vehicle_gtp'] = array( 'T4 FARRASINDO', 
									'T4', 
									"T4 AGUNG PUTRA", 
									"T4 NEW", 
									"T5", 
									"T5 PULSE",
									"T5 FUEL", 
									"T5 2WAY", 
									"T5DOOR", 
									"T5FAN", 
									"T5PTO",
								    "T5TAXI", 
									"T5SILVER", 
									"T5SUHU",
									"TMOTOR",
									"T8_2", 
									"TK309",
								    "TK309N",
									"TK309_NEW",
									"TK309LSA",
									"TK315LSA",
									"TK315",
									"TK315DOOR",
									"TK315N",
									"TK315DOOR_NEW",
									"TK315_NEW",
									"TK315FAN",
									"TK510",
									"TK510FAN",
									"TK510PTO",
									"TK510DOOR",
									"TK510CAM",
									"TK510CAMDOOR",
									"GT06",
									"GT06PINS",
									"GT06N",
									"GT06_NEW",
									"GT08S",
									"GT08SRFID",
									"GT08SPTO",
									"GT08SFAN",
									"GT08SDOOR",
									"GT08",
									"GT08FAN",
									"GT08PTO",
									"GT08CAM",
									"GT08DOOR",
									"GT08CAMDOOR",									
									"A13",
									"A14",
									"AT09",
									"X3",
									"X3_DOOR",
									"X3_PTO",
									"LT02",
									"LT03",
									"MT05S",
									"NR",
									"WETRACK",
									"MV03",
									"VT900",
									"VT900DOOR",
									"VT900FAN",
									"VT900PTO",
									"VT900BIB",
									"VT100",
									"VT200",
									"VT200DOOR",
									"VT200FAN",
									"VT200PTO",
									"VT200BIB",
									"HVT001",
									"MVT340",
									"VT202",
									"VT203"
								   );//ENGINE ON
								   
	$config['vehicle_gtp_door'] = array('T4 FARRASINDO', 
										'T4', 
										"T4 AGUNG PUTRA", 
										"T4 NEW");
	
	$config['vehicle_gtp_engine2'] = array('T4 FARRASINDO', 
											'T4', 
											"T4 AGUNG PUTRA", 
											"T4 NEW");
	
	$config['vehicle_t1'] = array('T1', 
								'T1_1', 
								"PLN", 
								"T1_U1");
	
	$config['vehicle_t3'] = array('T3');
	
	$config['vehicle_t5'] = array('T5', 
								'T5 PULSE', 
								'T5 2WAY', 
								'T6', 
								'T7', 
								'T5DOOR', 
								'T5FAN', 
								'T5PTO', 
								'T5TAXI', 
								'T5SILVER',
								'T5SUHU',
								'TK315DOOR');
	
	$config['vehicle_taxi'] = array('T5TAXI');
	
	$config['vehicle_pulse'] = array('T5 PULSE', 
									'T1', 
									'T1_1', 
									'T1_U1');
	
	$config['vehicle_fuel'] = array("T5 FUEL");
	
	$config['vehicle_odometer'] = array('T4',
										'T4 NEW',
										'T5', 
										'T5 PULSE',
										'T5 FUEL', 
										'T5 2WAY', 
										'T5DOOR', 
										'T5FAN', 
										'T5PTO', 
										'T5TAXI', 
										'T5SILVER',
										'T5SUHU',
										"TK315",
										"TK315DOOR",
										'TK315FAN',
										'TK315LSA',
										"TK315DOOR_NEW",
										"TK315_NEW",
										"TK315N",
										"TK309N",
										'TK309LSA',
										'TK309PTO',
										"TK309_NEW",
										'TK309',
										'TK510',
										'TK510FAN',
										'TK510PTO',
										'TK510DOOR',
										'TK510CAM',
										'TK510CAMDOOR',	
										'T8_2',
										"GT06N",
										'GT06_NEW',
										'GT06PINS',
										'GT08S',
										'GT08SFAN',
										'GT08SPTO',
										'GT08SRFID',
										'GT08SDOOR',
										'GT08',
										'GT08FAN',
										'GT08PTO',
										'GT08CAM',
										'GT08DOOR',
										'GT08CAMDOOR',										
										'A13',										
										'A14',										
										'AT09',
										"NR",																				
										'X3',
										'X3_DOOR',
										'X3_PTO',	
										'LT02',
										'LT03',
										"MT05S",
										'WETRACK',
										'MV03',
										'VT900',
										'VT900DOOR',
										"VT900FAN",
										"VT900PTO",
										"VT900BIB",
										"VT100",
										"VT200",
										"VT200DOOR",
										"VT200FAN",
										"VT200PTO",
										"VT200BIB",
										"HVT001",
										"MVT340",
										"VT202",
										"VT203",
										"AT5_RBT"
										);
	
	$config['vehicle_odometer_portable'] = array('AT5',
												'T13',
												'TK05');
	
	$config['vehicle_dbhistory'] = 2;
	
	$config['dbhistory_active'] = array("1"=>"GPS History 1",
										"2"=>"GPS History 2",
										"3"=>"GPS History 3");
	
	$config['user_view_payment'] = array('1',
										'53',
										'602', 
										'1412',
										'1877', 
										'1878', 
										'1945', 
										'2694', 
										'3186', 
										'3187');
	
	$config['DUMP_TABLE'] = array( "agent", 
									"announcement", 
									"bank", 
									"cctv", 
									"company", 
									"config", 
									"contactus", 
									"group", 
									"poi", 
									"poi_category", 
									"user", 
									"vehicle");
	
	$config['VTABLE'] = array( "INDOGPS"=>"indogps",	 
								"T1"=>"t1", 
								"T1_1"=>"t1_1", 
								"T1_U1"=>"t1_2",
								"PLN"=>"t1_pln", 
								"T3"=>"t3", 
								"T4"=>"t4", 
								"T4 FARRASINDO"=>"t4_farrasindo", 							
								"T4 NEW"=>"t4_new", 						  
								"T5"=>"t5", 
								"T5 FUEL"=>"t5_fuel", 
								"T5SUHU"=>"T5SUHU",							  
								"T7"=>"t7", 
								"TK303"=>"TK303",
								"TK309"=>"TK309",
								"TK309_NEW"=>"TK309_NEW",
								"TK309N"=>"TK309N",
								"TK309LSA"=>"TK309LSA",
								"TK315"=>"TK315",
								"TK315N"=>"TK315N",
								"TK315DOOR_NEW"=>"TK315DOOR_NEW",
								"TK315_NEW"=>"TK315_NEW",
								"TK315FAN"=>"TK315FAN",
								"TK315LSA"=>"TK315LSA",
								"TK510"=>"TK510",
								"TK510FAN"=>"TK510FAN",
								"TK510PTO"=>"TK510PTO",
								"TK510DOOR"=>"TK510DOOR",
								"TK510CAM"=>"TK510CAM",
								"TK510CAMDOOR"=>"TK510CAMDOOR",
								"TK05"=>"TK05",
								"T13"=>"T13",
								"GT06"=>"GT06",
								"GT06PINS"=>"GT06PINS",
								"GT06N"=>"GT06N",
								"GT06_NEW"=>"GT06_NEW",
								"GT08S"=>"GT08S",
								"GT08SRFID"=>"GT08SRFID",
								"GT08SFAN"=>"GT08SFAN",
								"GT08SPTO"=>"GT08SPTO",
								"GT08SDOOR"=>"GT08SDOOR",
								"GT08"=>"GT08",
								"GT08PTO"=>"GT08PTO",
								"GT08FAN"=>"GT08FAN",
								"GT08CAM"=>"GT08CAM",
								"GT08DOOR"=>"GT08DOOR",
								"GT08CAMDOOR"=>"GT08CAMDOOR",
								"A13"=>"A13",														  
								"A14"=>"A14",																																															 							  
								"AT09"=>"AT09",
								"X3"=>"X3",
								"X3_DOOR"=>"X3_DOOR",
								"X3_PTO"=>"X3_PTO",	
								"LT02"=>"LT02",
								"LT03"=>"LT03",
								"MT05S"=>"MT05S",	
								"WETRACK"=>"WETRACK",
								"NR"=>"NR",
								"NDROID"=>"NDROID",
								"MV03"=>"MV03",
								"VT900"=>"VT900",
								"VT900DOOR"=>"VT900DOOR",
								"VT900FAN"=>"VT900FAN",
								"VT900PTO"=>"VT900PTO",
								"VT900BIB"=>"VT900BIB",
								"VT100"=>"VT100",
								"VT200"=>"VT200",
								"VT200DOOR"=>"VT200DOOR",
								"VT200FAN"=>"VT200FAN",
								"VT200PTO"=>"VT200PTO",
								"VT200BIB"=>"VT200BIB",
								"HVT001"=>"HVT001",
								"MVT340"=>"MVT340",
								"VT202"=>"VT202",
								"VT203"=>"VT203",
								"AT5_RBT"=>"AT5_RBT"
								);

	$config['ALARMS'] = array(
				 "01"=>"SOS button is pressed"
				//,"02"=>"2nd button(call B)is pressed"
				//,"03"=>"3rd button(call C) is pressed"
				//,"04"=>"Reserved"
				,"10"=>"Low battery alarm"
				,"11"=>"over speed alar"
				,"12"=>"Geo fence alarm"
				//,"13"=>"Reserved"
				,"14"=>"Tracker units reset or power up alarm"
				,"15"=>"No GPS signal alarm"
				,"16"=>"Out of no GPS signal area alarm"
				,"20"=>"Cut off External Power Supply"
				,"21"=>"Input port low to high edge alarm, voltage of input port rise from 0V to 10V---------"
				,"31"=>"Input port high to low edge alarm, voltage of input port rise from 10V to 0V----------"
				,"72"=>"Direction Chang Alarm"
				);

	$config['table_hist']['INDOGPS'] = 'gps_hist_indogps';
	$config['table_hist']['PLN'] = 'gps_hist_t1_pln';
	$config['table_hist']['T1'] = 'gps_hist_t1';
	$config['table_hist']['T1_1'] = 'gps_hist_t1_1';
	$config['table_hist']['T3'] = 'gps_hist_t3';
	$config['table_hist']['T4'] = 'gps_hist_t4';
	$config['table_hist']['T4 FARRASINDO'] = 'gps_hist_t4_farrasindo';
	$config['table_hist']['T4 NEW'] = 'gps_hist_t4_new';
	$config['table_hist']['T1_U1'] = 'gps_hist_t1_2';
	$config['table_hist']['T5'] = 'gps_hist_t5';
	$config['table_hist']['T5 PULSE'] = 'gps_hist_t5_pulse';
	$config['table_hist']['T5 FUEL'] = 'gps_hist_t5_fuel';

	$config['table_hist_info']['INDOGPS'] = 'gps_info_hist_indogps';
	$config['table_hist_info']['PLN'] = 'gps_info_hist_t1_pln';
	$config['table_hist_info']['T1'] = 'gps_info_hist_t1';
	$config['table_hist_info']['T1_1'] = 'gps_info_hist_t1_1';
	$config['table_hist_info']['T3'] = 'gps_info_hist_t3';
	$config['table_hist_info']['T4'] = 'gps_info_hist_t4';
	$config['table_hist_info']['T4 FARRASINDO'] = 'gps_info_hist_t4_farrasindo';
	$config['table_hist_info']['T4 NEW'] = 'gps_info_hist_t4_new';
	$config['table_hist_info']['T1_U1'] = 'gps_info_hist_t1_2';
	$config['table_hist_info']['T5'] = 'gps_info_hist_t5';
	$config['table_hist_info']['T5 PULSE'] = 'gps_info_hist_t5_pulse';
	$config['table_hist_info']['T5 FUEL'] = 'gps_info_hist_t5_fuel';
	
	$config['restart_delay'] = 30;
	$config['ip_colo'] = '119.235.20.251';
	
	$config['vehicle_others'] = array(	'GT06',
										'GT06PINS',
										'GT06PTO', 
										'GT06N', 
										'TK303', 
										'TK309', 
										'TK309N', 
										'TK309_NEW',
										'TK309LSA',
										'TK309PTO',
										'TK315N', 										 
										'TK315DOOR', 
										'TK315_NEW',										 
										'TK315DOOR_NEW',
										'TK315',
										'TK315FAN',
										'TK315LSA',										
										'A13', 
										'AT5',
										'GT06_NEW',										
										'X3',
										'X3_DOOR',
										'X3_PTO',
										'WETRACK',
										'HVT001',
										'AT5_RBT'
										);
	$config['vehicle_others_coordinate'] = array('NR',
												'TJAM',
												'NDROID',
												'MV03',
												'VT100',
												'VT200',
												'VT200DOOR',
												'VT200FAN',
												'VT200PTO',
												'VT200BIB');
	
	$config['vehicle_no_engine'] = array('T1',
										'T1_1',
										'T1_U1',
										'T8',
										'TJAM',
										'T13',
										'TK05');
	
	$config['vehicle_workhour'] = array('TK510');
	$config['vehicle_cam'] = array('TK510CAM','TK510CAMDOOR','GT08CAM','GT08CAMDOOR');
