<?php
		//$config['template'] = 'transporter/';
		$config['template']                    = 'globalpage/';
		$config['logout']                      = 'http://transporter.lacak-mobil.com';
		$config['admin_template']              = 'admin/';
		$config['favicon']                     = "assets/transporter/images/truck_blue.ico";
		$config['license']                     = "www.lacak-mobil.com";
		$config['dir_photo']                   = "assets/transporter/images/photo/";
		$config['default_photo_driver']        = "default_photo_driver.png";
		$config['transporter_user_type_name']  = "Regular";
    $config['transporter_agent']           = 1;
		$config['interval_notification']       = 10000; //10 Detik
		$config['interval_geofence_alert']     = 20000; //20 Detik
		$config['interval_get_geofence_alert'] = 30000; //30 Detik
		$config['fan_app']                     = 1;
		$config['comment_app']                 = 1;
		$config['app_dosj_all']                = 1;
		$config["app_default"]                 = 1; // TRUE
		$config['company_view_dosj']           = array('571');
		//$config['GOOGLE_MAP_API_KEY']        = "AIzaSyDgDxL_3CpFInoeSmGy-oZElFJeKtgEUWA"; disable sementara , limit / block
		//$config['GOOGLE_MAP_API_KEY']        = "AIzaSyBozmLvDVGq6OtOdARowpV-mvUIkWQ_iGo";//intn
		// $config['GOOGLE_MAP_API_KEY']       = "AIzaSyCZPiEVU0FArY5NhXTmWGY1PrryadVmxs8";//prem
		$config['GOOGLE_MAP_API_KEY']          = "AIzaSyAYe-6_UE3rUgSHelcU1piLI7DIBnZMid4"; //csa
