<?php
		//$config['template'] = 'transporter/';
		$config['template'] = 'globalpage/';
		$config['logout'] = 'http://aryos.lacak-mobil.com';
		$config['admin_template'] = 'admin/';
		$config['favicon'] = "assets/transporter/images/truck_blue.ico";
		$config['license'] = "www.lacak-mobil.com";
		$config['dir_photo'] = "assets/transporter/images/photo/";
		$config['default_photo_driver'] = "default_photo_driver.png";
		$config['transporter_user_type_name'] = "Regular";
        $config['transporter_agent'] = 1;
		$config['interval_notification'] = 10000; //10 Detik
		$config['interval_geofence_alert'] = 20000; //20 Detik 
		$config['interval_get_geofence_alert'] = 30000; //30 Detik 		
		$config['fan_app'] = 1;
		$config['comment_app'] = 1;
		$config['app_dosj_all'] = 1;
		$config['company_view_dosj'] = array('571'); 
		$config['GOOGLE_MAP_API_KEY'] = "AIzaSyDxl6EvF2bY8iAM_fZnjpKZDA-zqSTfxHE";
